name: Github Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Completed
        run: echo "Completed the run of this pipeline"